// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event } from "mygo-runtime";

// ---- Types ----

/** SystemInfo describes the machine the app runs on. */
export interface SystemInfo {
  os: string;
  arch: string;
  goVersion: string;
}

// ---- Services ----

/**
 * Greeter is callable from the frontend: `mygo generate` turns its methods
 * into typed TypeScript functions in src/mygo.ts.
 */
export const Greeter = {
  /** Greet returns a greeting for name. */
  greet(name: string): Promise<string> {
    return call("Greeter.Greet", name);
  },
  /** Info returns information about the system. */
  info(): Promise<SystemInfo> {
    return call("Greeter.Info");
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  /** Tick is sent to the page every second. */
  tick: event<string>("tick"),
} as const;
